config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#search'

  # search_path (simple form)
  get 'search', to: 'pages#search'

  resources :books, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: "Added to wishlist"
    else
      render :new, status: :unprocessable_entity, alert: "Failed to add to wishlist"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
     params.require(:book).permit(:title, :author, :link, :image, :price, :store)
  end
end

app/controllers/pages_controller.rb
require 'uri'
require 'net/http'
require 'json'
require 'cgi'

class PagesController < ApplicationController
  def search
    return if params['/search'].nil?
    @query = params['/search'][:query]

    if @query.blank?
      flash[:alert] = "Please enter a search term."
      redirect_to root_path and return
    end

    # Get user's input, replace spaces, encode search term if it contains JP or CN characters
    search_term = @query.strip.gsub(' ', '%20')
    search_term = encode_search_term(search_term) if contains_japanese_or_chinese?(search_term)

    # Testing purpose
    # @amazon_search_results = search_amazon(search_term)

    @amazon_search_results = AmazonSearchService.call(search_term)
    # To add new book into wishlist we need to convert hash to book's instance
    # So that book instance can be use by simple form
    @amazon_search_results.each do |book|
      @book = Book.new(title: book[:title], author: book[:author], link: book[:link], image: book[:image], price: book[:price])
    end

    @kobo_search_results = KoboSearchService.call(search_term)
    unless @kobo_search_results.nil?
      @kobo_search_results.each do |book|
        @book = Book.new(title: book[:title], author: book[:author], link: book[:link], image: book[:image], price: book[:price])
      end
    end

    @google_search_results = GoogleSearchService.call(search_term)
    @google_search_results.each do |book|
      @book = Book.new(title: book[:title], author: book[:author], link: book[:link], image: book[:image], price: book[:price])
    end
  end

  private

  # Check whether the search term contains Japanese or Chinese
  def contains_japanese_or_chinese?(str)
    !!str.match(/[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\uff66-\uff9f\u4e00-\u9fa5]/)
  end

  # Encode Japanese and/or Chinese search term to use in URI
  def encode_search_term(search_term)
    CGI.escape(search_term)
  end

  # For view testing purpose (Free plan - 200 requests per month)
  def search_amazon(search_term)
    first_book = {
      title: "Eloquent JavaScript",
      author: "Marijn Haverbeke",
      link: "https://www.amazon.co.jp/Eloquent-JavaScript-3rd-Introduction-Programming-ebook/dp/B07C96Q217/ref=sr_1_1?keywords=eloquent+javascript+kindle&qid=1705379361&sr=8-1",
      image: "https://m.media-amazon.com/images/I/81HqVRRwp3L._AC_UL320_.jpg",
      price: "￥3,200"
    }
    second_book = {
      title: "Second book",
      author: "Marijn Haverbeke",
      link: "https://www.amazon.co.jp/Eloquent-JavaScript-3rd-Introduction-Programming-ebook/dp/B07C96Q217/ref=sr_1_1?keywords=eloquent+javascript+kindle&qid=1705379361&sr=8-1",
      image: "https://m.media-amazon.com/images/I/81HqVRRwp3L._AC_UL320_.jpg",
      price: "￥2,200"
    }
    third_book = {
      title: "Third book",
      author: "Marijn Haverbeke",
      link: "https://www.amazon.co.jp/Eloquent-JavaScript-3rd-Introduction-Programming-ebook/dp/B07C96Q217/ref=sr_1_1?keywords=eloquent+javascript+kindle&qid=1705379361&sr=8-1",
      image: "https://m.media-amazon.com/images/I/81HqVRRwp3L._AC_UL320_.jpg",
      price: "￥1,200"
    }

    # To test spinner
    sleep 3

    return [first_book, second_book, third_book]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_new.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.hidden_field :title, value: book[:title] %>
  <%= f.hidden_field :link, value: book[:link] %>
  <%= f.hidden_field :image, value: book[:image] %>
  <%= f.hidden_field :price, value: book[:price] %>
  <%= f.hidden_field :author, value: book[:author] %>
  <%= f.hidden_field :store, value: book[:store] %>
  <%= f.button :submit, "Add to wishlist", class: "btn btn-primary mt-2" %>
<% end %>

app/views/books/index.html.erb
<div class="container my-3">
  <h1>Wishlist</h1>
  <% if @books.empty? %>
    <p>No books in your wishlist</p>
  <% else %>
    <% @books.each do |book| %>
      <div class="card-product">
        <%= image_tag book.image, alt: book.title %>
        <div class="card-product-infos">
          <% if book.store === "Amazon" %>
            <span class="badge rounded-pill text-bg-warning mb-2">Amazon</span>
          <% end %>
          <% if book.store === "Rakuten Kobo" %>
            <span class="badge rounded-pill text-bg-danger mb-2">Rakuten Kobo</span>
          <% end %>
          <% if book.store === "Google Play Books" %>
            <span class="badge rounded-pill text-bg-primary mb-2">Google Play Books</span>
          <% end %>
          <h2><%= book.title %></h2>
          <p>Author: <%= book.author %></p>
          <p><%= book.price %></p>
          <%= link_to "Go to store", book.link, target: "_blank", class: "btn btn-primary btn-sm" %>
          <%= link_to book_path(book), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" do %>
            <i class="fa-solid fa-trash-can text-light"></i>
          <% end %>
        </div>
      </div>
      <br>
    <% end %>
  <% end %>
  <%= link_to "Back to home", root_path, class: "btn btn-primary" %>
</div>

app/views/books/new.html.erb
<% # For Rspec %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compare Ebooks' Prices</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/search.html.erb
<div data-controller="notice" class="container my-3">
  <h1>Compare Ebooks' Prices</h1>
  <div data-controller="spinner">
    <%= simple_form_for search_path, method: :get do |f| %>
      <div class="row row-cols-lg-auto g-1">
        <div class="col-lg-6">
          <%= f.input :query, label: false, placeholder: "Search..." %>
        </div>
        <div class="col-12">
          <%= f.button :submit, "Search", class: "btn btn-primary", data: { action: "click->spinner#showSpinner" } %>
        </div>
      </div>
    <% end %>
    <div data-spinner-target="spinner" class="spinner-border text-primary my-3 d-none" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
    <br>
  </div>
  <% if @query.present? %>
    <div class="d-flex gap-5">
      <div class="amazon">
        <h5>Amazon</h5>
        <% @amazon_search_results.each do |book| %>
          <div class="card mb-3" style="width: 14rem;">
            <%= image_tag book[:image], alt: book[:title], class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= book[:title] %></h5>
              <p class="card-text">Author: <%= book[:author].empty? ? "N/A" : book[:author] %></p>
              <p class="card-text"><%= book[:price].empty? ? "¥ 0" : book[:price] %></p>
              <%= link_to "Amazon Store", book[:link], target: "_blank", class: "btn btn-primary" %>
              <%= render "books/new", book: book %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="kobo">
        <h5>Kobo</h5>
        <% if @kobo_search_results.nil? %>
          <p>No search results</p>
        <% else %>
          <% @kobo_search_results.each do |book| %>
            <div class="card mb-3" style="width: 14rem;">
              <%= image_tag book[:image], alt: book[:title], class: "card-img-top" %>
              <div class="card-body">
                <h5 class="card-title"><%= book[:title] %></h5>
                <p class="card-text">Author: <%= book[:author].empty? ? "N/A" : book[:author] %></p>
                <% if book[:price].to_s.empty? %>
                  <% book[:price] = "¥ 0" %>
                <% else %>
                  <% book[:price] = number_to_currency(book[:price], { unit: "¥", precision: 0 }) %>
                <% end %>
                <p class="card-text"><%= book[:price] %></p>
                <%= link_to "Kobo Store", book[:link], target: "_blank", class: "btn btn-primary" %>
                <%= render "books/new", book: book %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="google">
        <h5>Google</h5>
        <% @google_search_results.each do |book| %>
          <div class="card mb-3" style="width: 14rem;">
            <%= image_tag book[:image], alt: book[:title], class: "card-img-top" %>
            <div class="card-body">
              <h5 class="card-title"><%= book[:title] %></h5>
              <p class="card-text">Author: <%= book[:author].nil? || book[:author].empty? ? "N/A" : book[:author] %></p>
              <p class="card-text">
                <% if book[:price].nil? %>
                  <%= "nil" %>
                <% elsif book[:price].empty? %>
                  <%= "¥ 0" %>
                <% else %>
                  <%= book[:price] %>
                <% end %>
              </p>
              <%= link_to "Google Play Books", book[:link], target: "_blank", class: "btn btn-primary" %>
              <%= render "books/new", book: book %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= link_to "Wishlist", books_path, class: "btn btn-primary" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>